name: Run Unit tests

on:
  push:
    branches: [ cvsimport ]

jobs:
  build_Windows:
    name: "Build for Windows"
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: '0'

      - name: override update version
        run: |
          git fetch
          git checkout cvsimport
          cp checkVersion.py ../checkVersion.py
          git checkout master
          cp ../checkVersion.py checkVersion.py
          python checkVersion.py
        shell: bash


      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          arch: 'win64_msvc2017_64'

      - name: Install CMake 
        uses: ilammy/msvc-dev-cmd@v1
      
      - name: Compile
        uses: lukka/run-cmake@v2
        with:
          cmakeGenerator: VS16Win64
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
          cmakeBuildType: Release
          cmakeAppendedArgs: '-DBUILD_LIBTIFF=ON'
          buildWithCMakeArgs: "--config Release --target ALL_BUILD"
          buildDirectory: ${{ github.workspace }}/build
          buildWithCMake: true
      
      - name: set up QT path
        run: |
          setx path "%path%;D:\a\Radiance\Qt\5.12.8\msvc2017_64\bin"
          setx path “%path%;D:\a\Radiance\Qt\5.12.8\msvc2017_64\lib”

      - name: Build installer
        uses: lukka/run-cmake@v2
        with:
          cmakeGenerator: VS16Win64
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
          cmakeBuildType: Release
          buildWithCMakeArgs: "--config Release --target PACKAGE"
          buildDirectory: ${{ github.workspace }}/build
          buildWithCMake: true
      
      - name: Zip Compiled Artifact
        run: |
          mv build\_CPack_Packages\win64\NSIS\radiance-*-Windows\ radiance
          Compress-Archive -U -Path radiance\* -DestinationPath Radiance_Windows

      - name: list files
        run: |
          mkdir WindowsBuild
          cp ./build/radiance-*.exe ./WindowsBuild/Radiance_Windows.exe
          cp ./Radiance_Windows.zip ./WindowsBuild/Radiance_Windows.zip
          ls -R
        shell: bash

      - name: Zip Build Artifact
        run: |
          Compress-Archive -U -Path WindowsBuild -DestinationPath Radiance_Windows_both

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: Radiance_Windows_both
          path: Radiance_Windows_both.zip

  build_OSX:
    name: "Build for OSX"
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      
      - name: override update version
        run: |
          git fetch
          git checkout cvsimport
          cp checkVersion.py ../checkVersion.py
          git checkout master
          cp ../checkVersion.py checkVersion.py
          python checkVersion.py
        shell: bash

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.8'

      - name: Install CMake 
        uses: ilammy/msvc-dev-cmd@v1
      
      
      - name: Install XQuartz
        run: |
          wget https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg
          sudo hdiutil attach XQuartz-2.7.11.dmg
          sudo installer -package /Volumes/XQuartz-2.7.11/XQuartz.pkg -target / 

      - name: Compile
        env:
          CMAKE_OSX_ARCHITECTURES: x86_64
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake ..
          make -j8

      - name: Build installer
        run: |
          export PATH=$PATH:$Qt5_DIR/bin
          export PATH=$PATH:$Qt5_DIR/lib

          cd build
          sudo cpack -G ZIP .
          echo "=============================="
          ls -R
          # sudo bash PackageMaker/Radiance/macInstall.sh

          cd ./_CPack_Packages/Darwin/ZIP/
          # cd build/_CPack_Packages/Darwin/PackageMaker/
          sudo cp -r ./radiance*/usr/local/radiance .
          ls
          sudo pkgbuild --identifier radiance.pkg --root "radiance" --install-location "/usr/local/radiance" radiance_Darwin.pkg
          sudo cp -r radiance_Darwin.pkg ../../../../Radiance_OSX.pkg
          du -h -d=0 *

        
      - name: Zip Build Artifact and list files
        run: |
          mkdir OSXBuild
          sudo cp Radiance_OSX.pkg ./OSXBuild/Radiance_OSX.pkg

          sudo mv ./build/_CPack_Packages/Darwin/ZIP/radiance-*-Darwin/usr/local/radiance ./radiance
          sudo zip -r Radiance_OSX.zip ./radiance
          sudo cp ./Radiance_OSX.zip ./OSXBuild/Radiance_OSX.zip

          sudo zip -r Radiance_OSX_both.zip ./OSXBuild
          ls -R
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: Radiance_OSX_both
          path: Radiance_OSX_both.zip

  build_Linux:
    name: "Build for Linux"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      
      - name: override update version
        run: |
          git fetch
          git checkout cvsimport
          cp checkVersion.py ../checkVersion.py
          git checkout master
          cp ../checkVersion.py checkVersion.py
          python checkVersion.py
        shell: bash

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.8'

      - name: Install CMake 
        uses: ilammy/msvc-dev-cmd@v1
      

      - name: set dev packages
        run: |
          sudo apt install libglu1-mesa-dev freeglut3-dev

      - name: Compile
        run: |
          export PATH=$PATH:$Qt5_DIR/bin
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j8

      - name: list files
        run: |
          cd $Qt5_DIR
          ls -R
        shell: bash

      - name: Build installer
        run: |
          export PATH=$PATH:$Qt5_DIR/bin
          export PATH=$PATH:$Qt5_DIR/lib
          cd build
          make package -j8

      - name: Zip Build Artifact
        run: |
          cd  ./build
          zip -r Radiance_Linux.zip radiance-*-Linux.tar.gz
          cp ./Radiance_Linux.zip ./../Radiance_Linux.zip
          

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: Radiance_Linux
          path: Radiance_Linux.zip

  Test_Windows:
    needs: [build_Windows]
    name: Test for Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v2
        with:
          ref: master
      
      - name: Download Windows installers
        uses: actions/download-artifact@v2
        with:
          name: Radiance_Windows_both
      
      - name: unzip artifacts
        run: |
          unzip Radiance_Windows_both.zip
          unzip WindowsBuild/Radiance_Windows.zip 
      
      - name: Display structure of downloaded files
        run: ls -R

      - name: install perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.30'
      

      - name: run tests -util
        shell: pwsh
        run: |
          $Env:RAYPATH = ".;${{ github.workspace }}\lib"
          $Env:PATH += ";${{ github.workspace }}\bin"
          rtrace -version
          cd ./test/util/
          make clean
          make -j8
      

      - name: run tests -gen
        shell: pwsh
        run: |
          $Env:RAYPATH = ".;${{ github.workspace }}\lib"
          $Env:PATH += ";${{ github.workspace }}\bin"
          rtrace -version

          cd ./test/gen/
          make clean
          make -j8

      - name: run tests -cal
        shell: pwsh
        run: |
          $Env:RAYPATH = ".;${{ github.workspace }}\lib"
          $Env:PATH += ";${{ github.workspace }}\bin"
          rtrace -version

          cd ./test/cal/
          make clean
          make -j8

      - name: run tests -px
        shell: cmd
        run: |
          set RAYPATH=.;${{ github.workspace }}\lib
          set PATH=%PATH%;${{ github.workspace }}\bin
          rtrace -version

          cd ./test/px/
          make clean
          make -j8
  
      - name: run tests -renders
        shell: cmd
        run: |
          set RAYPATH=.;${{ github.workspace }}\lib
          set PATH=%PATH%;${{ github.workspace }}\bin
          rtrace -version

          cd ./test/renders/
          make clean
          make
  

  Test_OSX:
    needs: [build_OSX]
    name: "Test for OSX"
    runs-on: macos-latest

    steps:
      - name: get os version
        run: |
          uname -a
          echo "=============================="
          sw_vers -productVersion


      - name: "Checkout Master Branch"
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Download OSX installers
        uses: actions/download-artifact@v2
        with:
          name: Radiance_OSX_both
      
      - name: unzip artifacts
        run: |
          unzip Radiance_OSX_both.zip
          unzip OSXBuild/Radiance_OSX.zip
      
      - name: Display structure of downloaded files
        run: ls -R
      
      - name: run tests -util
        run: |
          export RAYPATH=.:${{ github.workspace }}/radiance/lib
          export PATH=$PATH:${{ github.workspace }}/radiance/bin
          rtrace -version
          cd ./test/util/
          
          make clean
          make -j8
      
      - name: run tests -gen
        run: |
          export RAYPATH=.:${{ github.workspace }}/radiance/lib
          export PATH=$PATH:${{ github.workspace }}/radiance/bin
          rtrace -version
          cd ./test/gen/
          
          make clean
          make -j8

      - name: run tests -cal
        run: |
          export RAYPATH=.:${{ github.workspace }}/radiance/lib
          export PATH=$PATH:${{ github.workspace }}/radiance/bin
          rtrace -version
          cd ./test/cal/
          
          make clean
          make -j8

      - name: run tests -px
        run: |
          export RAYPATH=.:${{ github.workspace }}/radiance/lib
          export PATH=$PATH:${{ github.workspace }}/radiance/bin
          rtrace -version
          cd ./test/px/
          
          make clean
          make -j8

    
      - name: run tests -renders
        run: |
          export RAYPATH=.:${{ github.workspace }}/radiance/lib
          export PATH=$PATH:${{ github.workspace }}/radiance/bin
          rtrace -version

          cd ./test/renders/
          make clean
          make 

  Test_Linux:
    needs: [build_Linux]
    name: "Test for Linux"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Download Linux installers
        uses: actions/download-artifact@v2
        with:
          name: Radiance_Linux
      
      - name: unzip artifacts
        run: |
          unzip Radiance_Linux.zip
          ls
          echo "========== Extracting tar.gz ==========="
          tar -xvf radiance-*-Linux.tar.gz
          ls
          echo "========== Extracting tar ==========="
          

      - name: copy compiled folder
        run: |
          mkdir buildRad
          sudo cp -avr ./radiance-*-Linux/usr/local/radiance ./buildRad

      - name: Display structure of downloaded files
        run: ls -R

      - name: run tests -util
        run: |
          export RAYPATH=.:${{ github.workspace }}/buildRad/radiance/lib
          export PATH=$PATH:${{ github.workspace }}/buildRad/radiance/bin
          rtrace -version
          cd ./test/util/
          
          make clean
          make -j8
      
      - name: run tests -gen
        run: |
          export RAYPATH=.:${{ github.workspace }}/buildRad/radiance/lib
          export PATH=$PATH:${{ github.workspace }}/buildRad/radiance/bin
          rtrace -version
          cd ./test/gen/
          
          make clean
          make -j8

      - name: run tests -cal
        run: |
          export RAYPATH=.:${{ github.workspace }}/buildRad/radiance/lib
          export PATH=$PATH:${{ github.workspace }}/buildRad/radiance/bin
          rtrace -version
          cd ./test/cal/
          
          make clean
          make -j8

      - name: run tests -px
        run: |
          export RAYPATH=.:${{ github.workspace }}/buildRad/radiance/lib
          export PATH=$PATH:${{ github.workspace }}/buildRad/radiance/bin
          rtrace -version
          cd ./test/px/
          
          make clean
          make -j8

      - name: run tests -renders
        run: |
          export RAYPATH=.:${{ github.workspace }}/buildRad/radiance/lib
          export PATH=$PATH:${{ github.workspace }}/buildRad/radiance/bin
          rtrace -version

          cd ./test/renders/
          make clean
          make

      
